name: Free Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set RDP credentials
        run: |
          $password = "ali"
          net user runneradmin $password
          echo "RDP_PASSWORD=$password" >> $env:GITHUB_ENV

      - name: Install Tailscale
        run: |
          Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi -OutFile tailscale.msi
          msiexec /i tailscale.msi /quiet
          tailscale up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }} --hostname GitHubWindowsVM --accept-routes --accept-dns=false

      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Free console session
        run: tscon 1 /dest:console

      - name: Show connection info
        run: |
          echo "Tailscale IPv4 address:"
          tailscale ip -4
          echo "Username: runneradmin"
          echo "Password: $env:RDP_PASSWORD"
